In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,32,7],np.int8)

In [3]:
myarr

array([ 3,  6, 32,  7], dtype=int8)

In [4]:
myarr[0]

3

In [5]:
myarr.shape


(4,)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr[0]=98

In [8]:
myarr

array([98,  6, 32,  7], dtype=int8)

 # Arraycreation

In [9]:
listarray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [10]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 4)

In [13]:
listarray.size

12

In [14]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [16]:
zeros =np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rnge = np.arange(15)

In [19]:
rnge

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,50,10)

In [21]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22521646e-306, 1.02360460e-306, 7.56603882e-307],
       [1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.33511018e-306, 6.23057689e-307, 1.11260755e-306],
       [8.34453626e-308, 1.33508761e-307, 1.33511562e-306,
        8.90103560e-307, 1.42410974e-306, 1.42404727e-306]])

In [25]:
emp_like = np.empty_like(rnge)

In [26]:
emp_like

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1140,
          0,    0,    0,    0])

In [27]:
ide = np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr=arr.reshape(3,33)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr=arr.ravel()

In [38]:
arr.shape


(99,)

In [39]:
x= [[1,2,3],[4,5,6],[7,8,9]]

In [40]:
ar=np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ar.sum(axis=0)

array([12, 15, 18])

In [43]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [44]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
ar.flat

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [48]:
ar.ndim

2

In [49]:
ar.size

9

In [50]:
ar.nbytes

36

In [51]:
one=np.array([1,23,4,5,67,89])

In [53]:
one.argmax() #index where max le

5

In [54]:
one.argmin()

0

In [55]:
one.argsort()

array([0, 2, 3, 1, 4, 5], dtype=int64)

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar.argmin()

0

In [58]:
ar.argmax()

8

In [59]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [61]:
ar.max(axis=0)

array([7, 8, 9])

In [62]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [63]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [65]:
ar2= np.array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [66]:
ar +ar2

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [67]:
ar*ar2

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [69]:
ar.sum()

45

In [70]:
ar.min()

1

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [74]:
type(np.where(ar>5))

tuple

In [75]:
np.count_nonzero(ar)

9

In [76]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [77]:
import sys

In [78]:
ch_ar = [0,4,55,2]

In [79]:
np_ar = np.array(ch_ar)

In [80]:
sys.getsizeof(1)*len(ch_ar)

112

In [81]:
np_ar.itemsize *np_ar.size

16

In [83]:
np_ar.tolist()

[0, 4, 55, 2]